version: '3'
services:
  php:
    container_name: blank-laravel10-php-fpm
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/php-fpm/conf.d/user.ini:/usr/local/etc/php/conf.d/user.ini
    networks:
      - internal
  nginx:
    image: nginx
    container_name: blank-laravel10-nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8000:80'
    networks:
      - internal
  db:
      image: mariadb
      container_name: "${DB_HOST}"
      volumes:
          - ./docker/mariadb:/var/lib/mysql:Z
      environment:
          MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
          MARIADB_DATABASE: "${DB_DATABASE}"
          MARIADB_USER: "${DB_USERNAME}"
          MARIADB_PASSWORD: "${DB_PASSWORD}"
      ports:
          - '3306:3306'
      networks:
          - internal
  smtp:
      image: mailhog/mailhog
      container_name: laravel-blank-mailhog
      ports:
          - '1025:1025'
          - '8025:8025'
      networks:
          - internal

networks:
  internal:
    driver: bridge
