version: '3'
services:
  php:
    container_name: blank-laravel10-php-fpm
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./codebase:/var/www/html
      - ./docker/php-fpm/conf.d/user.ini:/usr/local/etc/php/conf.d/user.ini
    networks:
      - internal
  nginx:
    container_name: blank-laravel10-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8000:80'
    networks:
      - internal
networks:
  internal:
    driver: bridge
